apiVersion: v1
kind: Service
metadata:
  name: satellite-python-service
spec:
  selector:
    app: satellite
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 5000
  type: LoadBalancer


---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: satellite
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: satellite
    spec:
      containers:
      - name: satellite
        image: "gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ env.APPLICATION_NAME }}:latest"
        #imagePullPolicy: Never
        ports:
        - containerPort: 5000
